[package]
name = "example-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
zkbench = { path = "../zkbench" }
serde_json = "1.0"
git2 = "0.17"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "my_benchmark"
harness = false
