name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: self-hosted

    env:
      TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}  
      INGO_BENCHMARKS_DB_PASS: ${{ secrets.INGO_BENCHMARKS_DB_PASS }}

    steps:
      # Directory "common" will keep both ICICLE and bewnchmarks
    # - name: Checkout benchmarks repository
    #   uses: actions/checkout@v2
    #   with:
    #     repository: 'owner/repo1'
    #     path: 'parent_directory/repo1'

    # - name: Checkout zk-benchmarks repository
    #   uses: actions/checkout@v4
    #   with:
    #     repository: 'ingonyama-zk/zk-benchmarks'
    #     path: 'common/zk-benchmarks'

    # - name: configure git
    #   run: git config --global --add safe.directory /opt/icicle

    # - name: Benchmark add operation
    #   run: |
    #     cd ./benchmarks/add
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql

    # - name: Benchmark multiply operation
    #   run: |
    #     cd ./benchmarks/multiply
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql

    # - name: Benchmark MSM operation
    #   run: |
    #     cd ./benchmarks/msm
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql

    # - name: Benchmark NTT operation
    #   run: |
    #     cd ./benchmarks/ntt
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql
  
    - name: Benchmark Rust MSM operation
      run: |
        # cd ./benchmarks/rust/msm
        pwd
        ls -la
        nvidia-smi