name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: [self-hosted, benchmarks, icicle ]

    env:
      TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}  
      INGO_BENCHMARKS_DB_PASS: ${{ secrets.INGO_BENCHMARKS_DB_PASS }}

    steps:
    
    - name: Checkout zk-benchmarks repository
      uses: actions/checkout@v4

    - name: Check on repository
      run: |
        pwd
        ls -la

    - name: Build Docker image
      run: |
        docker build -t zk-benchmarks-image . 

    - name: Run a command inside a Docker container
      # -w /home/runner/zk-benchmarks
      run: docker run --rm --gpus all --name zk-benchmarks -v /home/docker/actions-runner/_work/zk-benchmarks/zk-benchmarks:/home/runner/zk-benchmarks  -w /home/runner/zk-benchmarks --user $(id -u):$(id -g) zk-benchmarks-image:latest /bin/bash -c "pwd && ls -la"

    - name: Benchmark Rust MSM operation
      run: |
        pwd
        ls -la
        #cargo criterion --message-format=json > ./criterion.json
        docker images
        #docker run --gpus all zk-benchmarks-image:latest
        

    # - name: Save Docker image
    #   run: |
    #     docker save zk-benchmarks-image:latest | gzip > zk-benchmarks-image.tar.gz

    # - name: configure git
    #   run: git config --global --add safe.directory /opt/icicle

    # - name: Benchmark add operation
    #   run: |
    #     cd ./benchmarks/add
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql

    # - name: Benchmark multiply operation
    #   run: |
    #     cd ./benchmarks/multiply
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql

    # - name: Benchmark MSM operation
    #   run: |
    #     cd ./benchmarks/msm
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql

    # - name: Benchmark NTT operation
    #   run: |
    #     cd ./benchmarks/ntt
    #     ./compile.sh
    #     ./run.sh
    #     cat ./benchmark.sql
  
    