name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: self-hosted
    env:
      TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}  
      INGO_BENCHMARKS_DB_PASS: ${{ secrets.INGO_BENCHMARKS_DB_PASS }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Clone Icicle
      uses: actions/checkout@v2
      with:
        repository: ingonyama-zk/icicle
        # path: /icicle
    # Add steps for your manual job

    - name: Run a command
      run: echo "Running on self-hosted runner"
    - name: Execute Script
      run: |
        chmod +x ./benchmarks/run-all-benchmarks.sh
        ./benchmarks/run-all-benchmarks.sh

