name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: self-hosted

    env:
      TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}  
      INGO_BENCHMARKS_DB_PASS: ${{ secrets.INGO_BENCHMARKS_DB_PASS }}

    steps:
    - name: Clone Icicle
      uses: actions/checkout@v2
      with:
        repository: ingonyama-zk/icicle
        # path: /icicle

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List Icicle contents
      run: ls -la

    - name: list files
      run: ls .. -la

    - name: Execute Script
      run: |
        pwd
        ls -la
        chmod +x ./benchmarks/run-all-benchmarks.sh
        ./benchmarks/run-all-benchmarks.sh

