name: Run Icicle Benchmarks

on: [push]

jobs:
    my_job:
      runs-on: self-hosted
      env:
        TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}  
        INGO_BENCHMARKS_DB_PASS: ${{ secrets.INGO_BENCHMARKS_DB_PASS }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run a command
          run: echo "Running on self-hosted runner"
        - name: Print Current Working Directory
          run: pwd
        - name: Use Secret
          run: echo $TEST_SECRET
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: ./benchmarks/Poseidon
            file: ./benchmarks/Poseidon/.devcontainer/Dockerfile
            load: true
            tags: zk-image:latest
        - name: Run Docker container
          run: |
            docker run -e INGO_BENCHMARKS_DB_PASS="${INGO_BENCHMARKS_DB_PASS}" -e TEST_SECRET="${TEST_SECRET}" --rm --gpus all  zk-image:latest /icicle-benchmark/run.sh
            # You can add additional commands here to interact with your container