name: Run Icicle Benchmarks

on:
    workflow_dispatch:

jobs:
    my_job:
      runs-on: self-hosted
      env:
        TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}  
        INGO_BENCHMARKS_DB_PASS: ${{ secrets.INGO_BENCHMARKS_DB_PASS }}
      steps:
        - name: Run a command
          run: echo "Running on self-hosted runner"
        - name: Print Current Working Directory
          run: pwd
